
package All_Reports.Excel_Report;


    import java.text.SimpleDateFormat;
    import java.util.Date;
    import java.util.Map;
    import java.util.TreeMap;
    import Config.*;
public class Debit_Order_Excel_Data {

  private static Debit_Order_Excel_Data data_instance;
  Map<String, Object[]> data = new TreeMap<String, Object[]>();
  int count;

  //Get the current date
  SimpleDateFormat formatter = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss z");

  public Debit_Order_Excel_Data() {
    count = 1;
    //Columns in your report
    data.put(String.valueOf(count),
        new Object[]{"Test Case Name ", "Dialog ID", "Execution Status", "Execution Date", "Comment"});
  }

  //Return number of rows to be added to the report
  public int getCount() {
    return count;
  }

  //Sigleton to return the current instance of a class or if there's no instance to create new one
  public static Debit_Order_Excel_Data getInstanceOfDebitOrder() {
    if (data_instance == null) {
      data_instance = new Debit_Order_Excel_Data();
    }
    return data_instance;
  }

  //Return the colomns and rows to be generated by the report
  public Map<String, Object[]> get_Data() {
    return data;
  }

  //Call this method to add new record
  public void set_Data(String TestCaseNameP, String dialagIdP,String results,String commentsP) {
    Date date = new Date();
    Log.info("This size of the map : "+data.size());
    count=getCount()+1;
    Log.info("Adding row number "+count+" to the test results");
    data.put(String.valueOf(count),
        new Object[]{TestCaseNameP, dialagIdP, results, formatter.format(date), commentsP});

    Log.info("This Test case is added to the list : "+TestCaseNameP);
    Log.info("This size of the map : "+data.size());
    Log.info("Test Case Name ************************    Dialog ID ******* Execution Status ************Execution Date ****************   Comment");
    Log.info(TestCaseNameP+"  "+ dialagIdP +"  "+results+"  "+formatter.format(date)+"  "+ commentsP);
  }

  //Call this method to add new record
  public void set_Data1(String TestCaseNameP, String dialagIdP,String results,String da,String commentsP) {
    Log.info("This size of the map : "+data.size());
    count=getCount()+1;
    Log.info("Adding row number "+count+" to the test results");
    data.put(String.valueOf(count),
        new Object[]{TestCaseNameP, dialagIdP, results, da, commentsP});
    Log.info("This Test case is added to the list : "+TestCaseNameP);
    Log.info("This size of the map : "+data.size());
  }
  int  count1=0;
  int passedNum=0;
  int failedNum=0;

  public int getFailedNum() {
    return failedNum;
  }
  public void setFailedNum(int failedNum) {
    this.failedNum = failedNum;
  }

  public int getPassedNum() {
    return passedNum;
  }
  public void setPassedNum(int passedNum) {
    this.passedNum = passedNum;
  }

  public void setCount1(int count) {
    this.count1 = count;
  }
  public int getCount1() {
    return count1;
  }
}
